Projecten2.NET/Controllers/CatalogusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Projecten2.NET.Models.DAL;
using Projecten2.NET.Models.Domain;
using Projecten2.NET.Models.Domain.IRepositories;
using Projecten2.NET.Models.ViewModels;

namespace Projecten2.NET.Controllers
{
    [Authorize]
    public class CatalogusController : Controller
    {
        private readonly IMateriaalRepository materiaalRepository;
        private readonly IDoelgroepRepository doelgroepRepository;
        private readonly ILeergebiedRepository leergebiedRepository;
        private readonly IGebruikerRepository gebruikerRepository;

        public CatalogusController(IMateriaalRepository materiaalRepository, IDoelgroepRepository doelgroepRepository, ILeergebiedRepository leergebiedRepository, IGebruikerRepository gebruikerRepository)
        {
            this.materiaalRepository = materiaalRepository;
            this.doelgroepRepository = doelgroepRepository;
            this.leergebiedRepository = leergebiedRepository;
            this.gebruikerRepository = gebruikerRepository;
        }
        // GET: Catalogus
        public ActionResult Index(Gebruiker gebruiker, string searchString, int doelgroepId=0, int leergebiedId=0)
        {
            try
            {
                IEnumerable<Materiaal> materialen;
                Doelgroep doelgroep;
                Leergebied leergebied;
                if (doelgroepId != 0)
                {
                    doelgroep = doelgroepRepository.FindById(doelgroepId);
                    materialen = doelgroep.Materialen.OrderBy(m => m.Artikelnaam);
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        materialen.Where(s =>
                            s.Artikelnaam.ToLower().Contains(searchString.ToLower()) ||
                            s.Omschrijving.ToLower().Contains(searchString.ToLower()));
                    }
                    ViewBag.Doelgroep = getDoelgroepSelectList(doelgroepId);
                    ViewBag.DoelgroepId = doelgroepId;
                    ViewBag.Leergebied = getLeergebiedSelectedList(leergebiedId);
                    ViewBag.LeergebiedId = leergebiedId;
                    return View(materialen.Select(m => new CatalogusViewModel(gebruiker, m)));
                }
                if (leergebiedId != 0)
                {
                    leergebied = leergebiedRepository.FindById(leergebiedId);
                    materialen = leergebied.Materialen.OrderBy(m => m.ArtikelNummer);
                    if (!string.IsNullOrEmpty(searchString))
                    {
                        materialen.Where(s =>
                            s.Artikelnaam.ToLower().Contains(searchString.ToLower()) ||
                            s.Omschrijving.ToLower().Contains(searchString.ToLower()));
                    }
                    ViewBag.Doelgroep = getDoelgroepSelectList(doelgroepId);
                    ViewBag.DoelgroepId = doelgroepId;
                    ViewBag.Leergebied = getLeergebiedSelectedList(leergebiedId);
                    ViewBag.LeergebiedId = leergebiedId;
                    return View(materialen.Select(m => new CatalogusViewModel(gebruiker, m)));

                }
                if (!string.IsNullOrEmpty(searchString))
                {
                    materialen = materiaalRepository.FindAll()
                            .Where(
                                s =>
                                    s.Artikelnaam.ToLower().Contains(searchString.ToLower()) ||
                                    s.Omschrijving.ToLower().Contains(searchString.ToLower()));
                }
                else
                {
                    materialen = materiaalRepository.FindAll().OrderBy(m => m.Artikelnaam).ToList();
                }

                ViewBag.Doelgroep = getDoelgroepSelectList(doelgroepId);
                ViewBag.DoelgroepId = doelgroepId;
                ViewBag.Leergebied = getLeergebiedSelectedList(leergebiedId);
                ViewBag.LeergebiedId = leergebiedId;
                return View(materialen.Select(m => new CatalogusViewModel(gebruiker, m)));
            }
            catch (Exception)
            {
                TempData["error"] = $"Er kunnen geen didactische leermiddelen worden opgehaald";
            }
            return View();
        }

        private SelectList getDoelgroepSelectList(int selectedValue = 0)
        {
            return new SelectList(doelgroepRepository.FindAll().OrderBy(d=>d.DoelgroepNaam), "DoelgroepId", "DoelgroepNaam", selectedValue);

        }

        private SelectList getLeergebiedSelectedList(int selectedValue = 0)
        {
            return new SelectList(leergebiedRepository.FindAll().OrderBy(l=>l.LeergebiedNaam),"LeergebiedId", "LeergebiedNaam", selectedValue);
        }

        public static implicit operator CatalogusController(CatalogusContext v)
        {
            throw new NotImplementedException();
        }
    }
}

Projecten2.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Didactische leermiddelen", "Index", "Catalogus", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        @if (User.IsInRole("Student"))
                        {

                            <li>@Html.ActionLink("Catalogus", "Index", "Catalogus")</li>
                            <li>@Html.ActionLink("Uw verlanglijst", "Index", "Verlanglijst")</li>
                            //<li>@{ Html.RenderAction("Overzicht", "Verlanglijst"); }</li>
                            <li>@Html.ActionLink("Uw reservaties", "Index", "Reservatie") </li>
                        }
                        else if (User.IsInRole("Personeel"))
                        {

                            <li>@Html.ActionLink("Catalogus", "Index", "Catalogus")</li>
                            <li>@Html.ActionLink("Uw verlanglijst", "Index", "Verlanglijst")</li>
                            <li>@Html.ActionLink("Uw blokkeringen", "Index", "Blokkering") </li>
                        }
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>  
    </div>
<div class="container body-content margin">
    @if (TempData["info"] != null)
    {
        <div class="alert alert-success">@TempData["info"]</div>
    }
    @if (TempData["error"] != null)
    {
        <div class="alert alert-warning">@TempData["error"]</div>
    }
    @RenderBody()



</div>

    <footer class="footer">

        <div class="">
            <div class="">
                <p >&copy; @DateTime.Now.Year - Faculteit Mens en Welzijn - Lerarenopleiding HoGent </p>
            </div>

           
        </div>

    </footer>

@Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>